name: sibna_dart
description: A high-performance secure messaging library for Flutter and Dart.
version: 1.0.0
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  http: ^1.0.0
  sqflite: ^2.0.0
  cryptography: ^2.5.0
  path: ^1.8.0
